### ISSUE TITLE
A lot of the Modrinth page is still the default color

### ISSUE THREAD

**Issue by SpvceR3ii** [worldwidepixel/blueRinth#3]
A lot of Modrinth is still the default color, despite changes being applied. 

This extension is an early test, and I love it, but there are some sharp edges such as the Download button, and the Modrinth logo at the top still following the default color scheme.

![image](https://github.com/user-attachments/assets/55305db5-4dfd-41c9-b74d-70e9b4e7c77a)

As you can see, the image shows that the default Modrinth page still follows the same format, with only 1-2 exceptions for the color format being followed. 

I am running the latest version of FireFox as this issue is being written. I really do enjoy the extension for the most part, and I must say, it does look good. The small issues do make it less immersive, but altogether it is an amazing extension. 

If you need me to do some testing for you, I'm awake 24/7.   - @SpvceR3ii

**Comment by worldwidepixel** [comment]
What colour did you switch to?

**Comment by SpvceR3ii** [comment]
![image](https://github.com/user-attachments/assets/728bae15-3fbb-479c-8487-c0b2d66255bb)

Vibrant Orange.

**Comment by SpvceR3ii** [comment]
![image](https://github.com/user-attachments/assets/62f5f1d1-96b4-4cb2-ad6d-914e0413918d)

As you can see, there are some changes being applied in the homepage, but seeing them in the actual mod pages are rare.

**Comment by worldwidepixel** [comment]
Try hard-reloading

**Comment by SpvceR3ii** [comment]
Alright.

**Comment by SpvceR3ii** [comment]
![image](https://github.com/user-attachments/assets/ecdc41ff-dfd3-47ea-89b1-8e6787814841)
Hard reload did nothing. still the same.

**Comment by worldwidepixel** [comment]
![image](https://github.com/user-attachments/assets/832153bf-8608-4d24-affe-93b1760a3f37)
I cannot reproduce your issue on Firefox.

**Comment by SpvceR3ii** [comment]
Hm. Let me try something.

**Comment by SpvceR3ii** [comment]
What other extensions are you using, and what steps have you taken?

**Comment by worldwidepixel** [comment]
I do not use any other extensions on Firefox, other than uBO. It would not change how this feature functions.

**Comment by SpvceR3ii** [comment]
So, I restarted a lot of my system, and completely forgot about the extension and it fixed itself. 

![image](https://github.com/user-attachments/assets/83379a52-4acc-4ea6-8a63-869798891faf)
It looks amazing, and the custom pastel colors also look great too. By far, my favorite color would be Pastel Blue, as it has a light tone which really lets you see a lot. 

I do wish that there was a red color, but by far, the extension looks amazing. Thank you so much.
